os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

env:
  global:
    - CONFIGURATION=Release
    - CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
#env:
#  global:
#    - PATH=$HOME/.local/bin:$PATH

#before_install:
#  - pip install --user awscli
#  - mkdir -p ~/artifacts
#  - aws s3 sync s3://cmake-seed/$TRAVIS_BUILD_NUMBER ~/artifacts
#
#after_success:
#  - aws s3 sync ~/artifacts s3://cmake-seed/$TRAVIS_BUILD_NUMBER
  
jobs:
  include:
    # Define jobs for pre-build stage    
    - stage: prebuild
      addons:
        apt:
          packages:
              - cppcheck
      script: 
        - |
          cppcheck --enable=information --template=gcc --enable=all -j4 --suppressions-list=cppcheck-suppressions.txt Lib/ App/ Test/
    - stage: prebuild
      addons:
        apt:
          packages:
              - clang-tidy-3.8
      cache:
        ccache: true
        directories:
          - $TRAVIS_BUILD_DIR/workspace/cmake
      install:
        - |
          if [ ! -d "$TRAVIS_BUILD_DIR/workspace/cmake/bin" ]; then
            travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/workspace/cmake
          fi
          export PATH=$TRAVIS_BUILD_DIR/workspace/cmake/bin:$PATH
      script: 
        - |
          mkdir Build
          cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DBUILD_APP=OFF -DBUILD_TEST=OFF -B./Build -H./
          cmake --build ./Build --config Release
          export PROJECT_FILES=$(find Lib -type f -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" -print)
          echo $PROJECT_FILES
          clang-tidy -p ./Build -checks=hicpp-* $PROJECT_FILES
    - stage: prebuild
      script: 
        - |
          echo "dependencies"