os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

jobs:
  include:
    # Define jobs for pre-build stage    
    - stage: prebuild
      script: 
        - |
          echo "pre-build job1"
              
    # Define jobs for build stage
    - stage: build
      script: 
        - |
          echo "build job"
          
    # Define jobs for post-build stage
    - stage: postbuild
      script: 
        - |
          echo "post-build job"

    # Define jobs for test stage
    - stage: test
      script: 
        - |
          echo "test job"
          
    # Define jobs for deploy stage
    - stage: deploy
      script: 
        - |
          echo "deploy job"