os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

#env:
#  global:
#    - PATH=$HOME/.local/bin:$PATH

#before_install:
#  - pip install --user awscli
#  - mkdir -p ~/artifacts
#  - aws s3 sync s3://cmake-seed/$TRAVIS_BUILD_NUMBER ~/artifacts
#
#after_success:
#  - aws s3 sync ~/artifacts s3://cmake-seed/$TRAVIS_BUILD_NUMBER
  
jobs:
  include:
    # Define jobs for pre-build stage    
    - stage: prebuild
      addons:
        apt:
          packages:
              - cppcheck
      script: 
        - |
          cppcheck --enable=information --template=gcc --enable=all -j4 --suppressions-list=cppcheck-suppressions.txt Lib/ App/ Test/
    - stage: prebuild
      addons:
        apt:
          packages:
              - clang-tidy-3.8
      script: 
        - |
          echo "clang-tidy"
          clang-tidy 
    - stage: prebuild
      script: 
        - |
          echo "dependencies"         
              
    # Define jobs for build stage
    - stage: build
      script: 
        - |
          echo "build x32"
    - stage: build
      script: 
        - |
          echo "build x64"
    - stage: build
      script: 
        - |
          echo "build coverage"          
          
    # Define jobs for post-build stage
    - stage: postbuild
      script: 
        - |
          echo "valgrind memcheck x32"
    - stage: postbuild
      script: 
        - |
          echo "valgrind memcheck x64"
    - stage: postbuild
      script: 
        - |
          echo "gcovr generate"

    # Define jobs for test stage
    - stage: test
      script: 
        - |
          echo "report coverage"
    - stage: test
      script: 
        - |
          echo "unit test"
    - stage: test
      script: 
        - |
          echo "validation test"
          
    # Define jobs for deploy stage
    - stage: deploy
      script: 
        - |
          echo "github"