os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

env:
  global:
    - CONFIGURATION=Release
    - CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"

jobs:
  include:
    # cppcheck
    - stage: prebuild
      addons:
        apt:
          packages:
              - cppcheck
      script: 
        - |
          cppcheck --enable=information --template=gcc --enable=all --suppressions-list=cppcheck-suppressions.txt Lib/ App/ Test/
    # clang-tidy
    - stage: prebuild
      addons:
        apt:
          packages:
              - clang-tidy-3.8
      cache:
        ccache: true
        directories:
          - $TRAVIS_BUILD_DIR/Workspace/CMake
          - $TRAVIS_BUILD_DIR/Build
      install:
        - |
          if [ ! -d "$TRAVIS_BUILD_DIR/Workspace/CMake/bin" ]; then
            travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/Workspace/CMake
          fi
          export PATH=$TRAVIS_BUILD_DIR/Workspace/CMake/bin:$PATH
      script: 
        - |
          cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_APP=OFF -DBUILD_TEST=OFF -B./Build -H./
          cmake --build ./Build --config $CONFIGURATION
          export PROJECT_FILES=$(find Lib -type f -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h")
          clang-tidy -p ./Build -checks=hicpp-*,modernize-*,cppcoreguidelines-*, $PROJECT_FILES
    # Extern project
    - &ExternBuild
      stage: prebuild
      addons:
        apt:
          packages:
              - $COMPILER
      cache:
        ccache: true
        directories:
          - $TRAVIS_BUILD_DIR/Workspace/CMake
          - $TRAVIS_BUILD_DIR/Build
      before_install:
        - |
          pip install --user awscli
      install:
        - |
          if [ ! -d "$TRAVIS_BUILD_DIR/Workspace/CMake/bin" ]; then
            travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/Workspace/CMake
          fi
      before_script:
       - |
          export PATH=$HOME/.local/bin:$PATH
          export PATH=$TRAVIS_BUILD_DIR/Workspace/CMake/bin:$PATH
          
          if [ $ARCH = "64" ]; then
            export CXX_FLAGS="-m64"
          elif
            export CXX_FLAGS="-m32"
          fi
      script: 
        - |
          cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS=$CXX_FLAGS -B./Build -H./Extern
          cmake --build ./Build --target all --config $CONFIGURATION
      after_success:
        - |
          aws s3 sync Build/Install s3://$TRAVIS_REPO_SLUG/extern/$OS/$ARCH
     - <<: *ExternBuild
      env:
        - OS="linux"
        - COMPILER="gcc"
        - ARCH="32"
    - <<: *ExternBuild
      env:
        - OS="linux"
        - COMPILER="gcc"
        - ARCH="64"
    - <<: *ExternBuild
      env:
        - OS="windows"
        - COMPILER="gcc-mingw-w64"
        - ARCH="32"
    - <<: *ExternBuild
      env:
        - OS="windows"
        - COMPILER="gcc-mingw-w64"
        - ARCH="64"