os: linux
sudo: false
language: cpp
compiler: g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"

install:
  - |
    if [ "$CXX" = "g++" ]; then 
      export CXX="g++-5" CC="gcc-5"; 
    fi
  - |
    if [ ! -f "${TRAVIS_BUILD_DIR}/tmp/cmake/cached" ]; then     
      mkdir -p ${TRAVIS_BUILD_DIR}/tmp/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/tmp/cmake          
      touch ${TRAVIS_BUILD_DIR}/tmp/cmake/cached
    fi
    export PATH=${TRAVIS_BUILD_DIR}/tmp/cmake/bin:${PATH}
    export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

before_script:
  - cmake -G "Unix Makefiles" -B./Build -H./ -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/Install -DCMAKE_CXX_FLAGS=${CXX_FLAGS}
    
script:    
  - |
    push Build
    make install
    pop
    
after_success:
  - |
    push Build
    make test
    pop

before_deploy:
  - |
    push Build
    make package
    pop
  
