os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

jobs:
  include:
    # Define jobs for pre-build stage    
    - stage: prebuild
      script: 
        - |
          echo "pre-build job1"
    - stage: prebuild
      script: 
        - |
          echo "pre-build job2"
    - stage: prebuild
      script: 
        - |
          echo "pre-build job3" >> tmp.txt
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        target_branch: artifacts
        local_dir: $TRAVIS_BUILD_ID
        file:
          - tmp.txt
              
    # Define jobs for build stage
    - stage: build
      script: 
        - |
          echo "build job1"
    - stage: build
      script: 
        - |
          echo "build job2"      
          
    # Define jobs for post-build stage
    - stage: postbuild
      script: 
        - |
          echo "post-build job1"
    - stage: postbuild
      script: 
        - |
          echo "post-build job2"
    - stage: postbuild
      script: 
        - |
          echo "post-build job3"

    # Define jobs for test stage
    - stage: test
      script: 
        - |
          echo "test job1"
    - stage: test
      script: 
        - |
          echo "test job2"
          
    # Define jobs for deploy stage
    - stage: deploy
      script: 
        - |
          echo "deploy job"