os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

#env:
#  global:
#    - PATH=$HOME/.local/bin:$PATH

#before_install:
#  - pip install --user awscli
#  - mkdir -p ~/artifacts
#  - aws s3 sync s3://cmake-seed/$TRAVIS_BUILD_NUMBER ~/artifacts
#
#after_success:
#  - aws s3 sync ~/artifacts s3://cmake-seed/$TRAVIS_BUILD_NUMBER
  
jobs:
  include:
    # Define jobs for pre-build stage    
    - stage: prebuild
      addons:
        apt:
          packages:
              - cppcheck
      script: 
        - |
          cppcheck --enable=information --template=gcc --enable=all -j4 --suppressions-list=cppcheck-suppressions.txt Lib/ App/ Test/
    - stage: prebuild
      addons:
        apt:
          packages:
              - clang-tidy-3.8
      script: 
        - |
          mkdir Build
          cmake -G "Unix Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -B./Build -H./
          cmake --build ./Build --config Release
          export PROJECT_FILES=$(find ./Lib -name "*.{h,cpp}")
          echo $PROJECT_FILES
          clang-tidy -p ./Build -checks=* $PROJECT_FILES
    - stage: prebuild
      script: 
        - |
          echo "dependencies"