os: linux
sudo: false
language: cpp

# Define order of project stages
stages:
  - prebuild
  - build
  - postBuild
  - test
  - deploy

env:
  global:
    - CONFIGURATION=Release
    - CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"

jobs:
  include:
    # Extern project
    - &ExternBuild
      stage: prebuild
      env:
        - OS="Linux"
        - ARCH="32"
      addons:
        apt:
          packages:
              - g++
      cache:
        ccache: true
        directories:
          - $TRAVIS_BUILD_DIR/Workspace/CMake
          - $TRAVIS_BUILD_DIR/Build
      before_install:
        - |
          pip install --user awscli
      install:
        - |
          if [ ! -d "$TRAVIS_BUILD_DIR/Workspace/CMake/bin" ]; then
            travis_retry wget --no-check-certificate --quiet -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/Workspace/CMake
          fi
      before_script:
       - |
          export PATH=$HOME/.local/bin:$PATH;
          export PATH=$TRAVIS_BUILD_DIR/Workspace/CMake/bin:$PATH;
          
          if [ $ARCH = "64" ]; then
            export CXX_FLAGS="-m64";
          elif [ $ARCH = "32" ]; then
            export CXX_FLAGS="-m32";
          fi
          
          if [ $OS = "Linux" ]; then
            export CXX="g++" CC="gcc";
          elif [ $OS = "Windows" ]; then
            export CXX="x86_64-w64-mingw32-g++" CC="x86_64-w64-mingw32-gcc";
          fi
      script: 
        - |
          cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS=$CXX_FLAGS -B./Build -H./Extern
          cmake --build ./Build --target all --config $CONFIGURATION
      after_success:
        - |
          aws s3 sync Build/Install s3://$TRAVIS_REPO_SLUG/extern/$OS/$ARCH
    - <<: *ExternBuild
      env:
        - OS="Linux"
        - ARCH="64"
      addons:
        apt:
          packages:
            - g++
    - <<: *ExternBuild
      env:
        - OS="Windows"
        - ARCH="32"
      addons:
        apt:
          packages:
            - g++-mingw-w64
    - <<: *ExternBuild
      env:
        - OS="windows"
        - ARCH="64"
      addons:
        apt:
          packages:
            - g++-mingw-w64