DockerLinux: &ExecutorLinux
  working_directory: /tmp
  docker:
    - image: cristianszabo/gnu-linux:7.1

BuildExtern: &BuildExternBase
  steps:
    - checkout
    - restore_cache:
        key: v1-build-extern-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: Build Project Dependencies
        command: |
          cmake -G "Unix Makefiles" -B./Build -H./
          cmake --build ./Build --config $CONFIGURATION
    - save_cache:
        key: v1-build-extern-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - Build  
    - persist_to_workspace:
          root: Build/Install
          paths:
            - echo-output
    
version: 2
jobs:
  BuildExternLinux32:
    <<: *ExecutorLinux
    <<: *BuildExternBase
    environment:
      OS: Linux
      ARCH: 32
  BuildExternLinux64:
    <<: *ExecutorLinux
    <<: *BuildExternBase
    environment:
      OS: Linux
      ARCH: 64
  BuildProjectLinux32:
    <<: *ExecutorLinux
    steps:
      - run:
        command: |
          echo "test"          
  BuildProjectLinux64:
    <<: *ExecutorLinux
    steps:
      - run:
        command: |
          echo "test"          
  TestProjectLinux:
    <<: *ExecutorLinux
    steps:
      - run:
        command: |
          echo "test"   
  DeployGithub:
    <<: *ExecutorLinux
    steps:
      - run:
        command: |
          echo "test"

workflows:
  version: 2

  BuildLinux:
    jobs:
      - BuildExternLinux32
      - BuildExternLinux64
      - BuildProjectLinux32:
          requires:
            - BuildExternLinux32
      - BuildProjectLinux64:
          requires:
            - BuildExternLinux64
      - TestProjectLinux:
          requires:
            - BuildProjectLinux32
            - BuildProjectLinux64
      - DeployGithub:
          requires:
            - TestProjectLinux