ExternalProject_Add (
    Docopt

    GIT_REPOSITORY "https://github.com/docopt/docopt.cpp.git"
    GIT_TAG "master"
       
    CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
    
    UPDATE_COMMAND "")

ExternalProject_Get_Property (Docopt INSTALL_DIR)

set (PROJECT_NAME "docopt")

set (DEST_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR})

if (WIN32)
    set (DEST_INSTALL_DIR ${CMAKE_INSTALL_BINDIR})
endif ()

file (MAKE_DIRECTORY "${INSTALL_DIR}/include/${PROJECT_NAME}")

add_library (${PROJECT_NAME} SHARED IMPORTED)

set_target_properties (${PROJECT_NAME} PROPERTIES
	IMPORTED_LOCATION "${INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}${PROJECT_NAME}${CMAKE_SHARED_LIBRARY_SUFFIX}"
    IMPORTED_IMPLIB "${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}${PROJECT_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX}"
    INTERFACE_INCLUDE_DIRECTORIES "${INSTALL_DIR}/include/${PROJECT_NAME}")
    
add_dependencies (${PROJECT_NAME} Docopt)

get_target_property(EXPORT_FILE_NAME ${PROJECT_NAME} IMPORTED_LOCATION)

install (FILES ${EXPORT_FILE_NAME}
    DESTINATION ${DEST_INSTALL_DIR} COMPONENT Applications)
